### PR TITLE
Don't include tests/* and other files  in published package.

### LINKED ISSUE #26: publishes /tests/* by mistake
publishes /tests/* by mistake

### PR DESCRIPTION
**Pull request by abuiles**
Fixes #26.

### CODE REVIEW

**Comment by locks** [comment]
Are you going with this approach or with the `files` whitelist one in package.json?

**Comment by stefanpenner** [comment]
> Are you going with this approach or with the files whitelist one in package.json?

files might be best.

**Comment by abuiles** [comment]
yeah, files. I'll try to update it shortly .

**Comment by abuiles** [comment]
@locks actually, if you have some bandwidth... go ahead.. I'll close this one...

**Comment by locks** [comment]
Thanks @abuiles :) Superseded by https://github.com/ember-cli/ember-router-generator/pull/29.

**Pull request closed without merging**
