### PR TITLE
Add support for custom identifiers other than 'route'

### PR DESCRIPTION
**Pull request by trentmwillis**
Addresses #20. Since it was relatively straightforward I figured I'd implement it and see what happens.

### CODE REVIEW

**Comment by stefanpenner** [comment]
Although i suspect it works, I would love to see a test that tests various nested variants of this work.

**Comment by trentmwillis** [comment]
@stefanpenner added more tests. Currently, if you try to generate a nested mount it will create all new levels as mount statements; I'm not sure this lines up correctly with Engines. The alternative is to add logic such that custom identifiers are only used on leaf nodes.

**Comment by stefanpenner** [comment]
this LGTM, thanks.

@rwjblue @dgeb thoughts on merging? Although engines aren't public API yet, this specific addition to the generators seems alright, but would love your input.

**Comment by rwjblue** [comment]
This seems good to me.  Also makes it possible for torii to do `this.authenticatedRoute('my-account');`.

/cc @mixonic

**Comment by stefanpenner** [comment]
tags as v1.2.0 but I apparently don't have publish privs.

cc @abuiles can you add me and rob to the npm owners for this module?

**Comment by stefanpenner** [comment]
señor @abuiles has release v1.2.0

**Comment by abuiles** [comment]
Also, you are owners in npm  now :)

**Pull request merged**
